// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed JetBrainsMono-Regular.ttf
var resourceJetBrainsMonoRegularTtfData []byte
var resourceJetBrainsMonoRegularTtf = &fyne.StaticResource{
	StaticName:    "JetBrainsMono-Regular.ttf",
	StaticContent: resourceJetBrainsMonoRegularTtfData,
}
