// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wiz} from '../models';
import {config} from '../models';
import {main} from '../models';

export function DeleteDevice(arg1:string):Promise<void>;

export function DeleteGroup(arg1:string):Promise<void>;

export function Discover():Promise<Array<wiz.Device>>;

export function GetConfig():Promise<config.Config>;

export function GetState(arg1:string,arg2:string):Promise<main.StateResult>;

export function GroupTargets(arg1:string):Promise<Array<main.Target>>;

export function SaveDevice(arg1:config.SavedDevice):Promise<void>;

export function SaveGroup(arg1:config.Group):Promise<void>;

export function SetLastState(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetPilot(arg1:Array<main.Target>,arg2:Record<string, any>):Promise<main.FanoutResult>;

export function SetPower(arg1:Array<main.Target>,arg2:boolean):Promise<main.FanoutResult>;

export function SetTheme(arg1:string):Promise<void>;
