// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DeleteDevice(arg1) {
  return window['go']['main']['App']['DeleteDevice'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function Discover() {
  return window['go']['main']['App']['Discover']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetState(arg1, arg2) {
  return window['go']['main']['App']['GetState'](arg1, arg2);
}

export function GroupTargets(arg1) {
  return window['go']['main']['App']['GroupTargets'](arg1);
}

export function OpenReleases() {
  return window['go']['main']['App']['OpenReleases']();
}

export function SaveDevice(arg1) {
  return window['go']['main']['App']['SaveDevice'](arg1);
}

export function SaveGroup(arg1) {
  return window['go']['main']['App']['SaveGroup'](arg1);
}

export function SetLastState(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetLastState'](arg1, arg2, arg3);
}

export function SetPilot(arg1, arg2) {
  return window['go']['main']['App']['SetPilot'](arg1, arg2);
}

export function SetPower(arg1, arg2) {
  return window['go']['main']['App']['SetPower'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}
